# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartUI
  pod 'SDWebImage','5.19.0'
  pod 'AFNetworking', '4.0.1'
  pod 'Masonry', '1.1.0'
  pod 'IQKeyboardManager'
  pod 'SnapKit'
  pod 'YTKNetwork','3.0.6'
  pod 'LookinServer'
  pod 'MJExtension'
  pod 'GTMBase64'
  #pod 'CommonCrypto'
  pod 'insideSDK', :path => '../insideSDK'
  pod 'SkeletonView'
  pod 'KakaJSON'
  pod 'Alamofire','4.9.1'
  pod 'CryptoSwift',:git =>'https://github.com/krzyzanowskim/CryptoSwift.git'
end

def pods_xcode15_compatibility
  post_integrate do |installer|
    compiler_flags_key = 'COMPILER_FLAGS'
    project_path = 'Pods/Pods.xcodeproj'

    project = Xcodeproj::Project.open(project_path)
    project.targets.each do |target|
      target.build_phases.each do |build_phase|
        if build_phase.is_a?(Xcodeproj::Project::Object::PBXSourcesBuildPhase)
          build_phase.files.each do |file|
            if !file.settings.nil? && file.settings.key?(compiler_flags_key)
              compiler_flags = file.settings[compiler_flags_key]
              file.settings[compiler_flags_key] = compiler_flags.gsub(/-DOS_OBJECT_USE_OBJC=0\s*/, '')
            end
          end
        end
      end
    end
    project.save()
  end
end


def pods_close_bitcode
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/-framework "UniformTypeIdentifiers"/, "-weak_framework \"UniformTypeIdentifiers\"")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end
      end
    end
  end
end
